version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kinepro_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: valentinaNegra
      POSTGRES_PASSWORD: valentinaNegra
      POSTGRES_DB: kinepro_db
    ports:
      - "5432:5432"
    volumes:
      - kinepro_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U valentinaNegra -d kinepro_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  kinepro_pg_data: